apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: default-backend-service
spec:
  ports:
    - name: mathchere-http
      port: 80
      targetPort: 80
  selector:
    io.ian.service: frontend