apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.ian.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.ian.service: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.ian.network/match-network: "true"
        io.ian.service: frontend
    spec:
      containers:
        - image: happyostrich/matchhere_frontend:latest
          name: frontend
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
