apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.ian.service: frontend
  name: frontend
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    io.ian.service: frontend
status:
  loadBalancer: {}
