apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: "ALLOW_ANONYMOUS_LOGIN"
          value: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka
        id: "1"
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: "ALLOW_PLAINTEXT_LISTENER"
          value: "yes"
        - name: "KAFKA_CFG_LISTENERS"
          value: "PLAINTEXT://:9092"
        - name: "KAFKA_CFG_ZOOKEEPER_CONNECT"
          value: "zookeeper:2181"
        - name: "KAFKA_BROKER_ID"
          value: "1"
        - name: "KAFKA_CFG_ADVERTISED_LISTENERS"
          value: "PLAINTEXT://kafka:9092"