apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: match-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.ian.network/match-network: "true"
  podSelector:
    matchLabels:
      io.ian.network/match-network: "true"
