apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchhere-mysql
  labels:
    app: matchhere
spec:
  selector:
    matchLabels:
      app: matchhere
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matchhere
        tier: mysql
    spec:
      containers:
      - image: happyostrich/matchhere_mysql
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: mysql-root-pass
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-db-url
                key: database
          - name: MYSQL_INITDB_SKIP_TZINFO
            value: "yes"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        # - name: mysql-init-config
        #   mountPath: /docker-entrypoint-initdb.d/
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        
      volumes:
      # - name: mysql-init-config
      #   configMap:
      #     name: mysql-initdb-config
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      