apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.ian.network/match-network: "true"
    io.ian.service: mysql
  name: mysql
spec:
  containers:
    - args:
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
      env:
        - name: MYSQL_DATABASE
          value: matching
        - name: MYSQL_ROOT_PASSWORD
          value: madmin
        - name: TZ
          value: Asia/Seoul
      image: mysql:8.0.26
      name: mysql
      ports:
        - containerPort: 3306
      resources: {}
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: mysql-claim0
  restartPolicy: OnFailure
  volumes:
    - name: mysql-claim0
      persistentVolumeClaim:
        claimName: mysql-claim0
status: {}
