apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: madmin
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/matching
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          image: happyostrich/matchhere_spring
          name: spring
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: regcred
