apiVersion: v1
kind: Service
metadata:
  name: spring-env-svc
  labels:
    app: spring-env-svc
spec:
  type: NodePort
  ports:
    - name: server
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: was
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  labels:
    app: spring-svc
spec:
  ports:
    - name: server
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: was
# apiVersion: v1
# kind: Service
# metadata:
#   name: matchhere-spring
#   labels:
#     app: matchhere-spring
# spec:
#   ports:
#     - port: 8080
#   selector:
#     app: matchhere-spring
#   clusterIP: None
# apiVersion: v1
# kind: Service
# metadata:                     
#   name: matchhere-spring
#   labels:
#     app: matchhere-spring
# spec:                         
#   type: NodePort
#   selector:
#     app: matchhere-spring
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 8080