apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.ian.service: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.ian.service: spring
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.ian.network/match-network: "true"
        io.ian.service: spring
    spec:
      containers:
        - env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: madmin
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/matching
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          image: happyostrich/matchhere_spring
          name: spring
          ports:
            - containerPort: 8080
          resources: {}
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
