apiVersion: v1
kind: Service
metadata:                     
  name: matchhere-spring
  labels:
    app: matchhere-spring
spec:                         
  type: NodePort
  selector:
    app: matchhere-spring
  ports:
  - name: http
    port: 8080
    targetPort: 8080