apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.ian.service: spring
  name: spring
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.ian.service: spring
status:
  loadBalancer: {}
