apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchhere-spring
  labels:
    app: matchhere-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchhere-spring
  template:
    metadata:
      labels:
        app: matchhere-spring
    spec:
      containers:
      - name: matchhere-spring
        image: happyostrich/matchhere_spring:latest
        # imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        # resources:
        #   limits:
        #     cpu: 0.2
        #     memory: "200Mi"
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
      imagePullSecrets:
      - name: regcred